# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0004_renta_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renta',
            name='municipio',
        ),
    ]
