# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0006_renta_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='rentas')),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentas.Renta')),
            ],
        ),
    ]
