# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0009_auto_20161123_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='renta',
            name='aire',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='comidas',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='desayunos',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='refrigerador',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='taxi',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='tv',
        ),
        migrations.AlterField(
            model_name='galeria',
            name='renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentas.Renta'),
        ),
        migrations.AddField(
            model_name='renta',
            name='servicio',
            field=models.ManyToManyField(to='rentas.Servicio'),
        ),
    ]
