# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-03 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0016_auto_20161129_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='direccion',
            field=models.TextField(default='Dirección del inmueble', verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='renta',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='renta',
            name='movil',
            field=models.TextField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='renta',
            name='propietario',
            field=models.CharField(default='Propietario', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renta',
            name='telefono',
            field=models.TextField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentas.Renta'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentas.Renta'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentas.Renta'),
        ),
    ]
